# Generated by Django 2.2.6 on 2020-03-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='category',
        ),
        migrations.RemoveField(
            model_name='index',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='IndexSize',
        ),
        migrations.RemoveField(
            model_name='indexsubcategory',
            name='mycategory',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='IndexCategory',
        ),
        migrations.DeleteModel(
            name='IndexSubCategory',
        ),
    ]
